import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.awt.event.ActionEvent;

/**
 *
 * @author manoel
 */
public class PlayerWindow extends javax.swing.JFrame {

    /**
     * Creates new form PlayerWindow
     */
    public PlayerWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        //albumCover = new Image("res/default_cover.png");
        jScrollPane1 = new JScrollPane();
        songTable = new JTable();
        leftPanel = new JPanel();
        controlPanel = new JPanel();
        inferiorPanel = new JPanel();
        separatorLabel = new JLabel();
        startTimeLabel = new JLabel();
        endTimeLabel = new JLabel();
        timeSlider = new JSlider();
        volumeSlider = new JSlider();
        selectFolder = new JButton();
        playPauseButton = new JButton();
        previousButton = new JButton();
        nextButton = new JButton();
        replayButton = new JButton();
        stopButton = new JButton();
        muteButton = new JButton();
        appPlayer = new AppPlayer(timeSlider);
        toggleReplay = false;
        disableSkip = false;

        setLocation(getToolkit().getScreenSize().width/3, getToolkit().getScreenSize().height/6);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        inferiorPanel.setBackground(new Color(30, 80, 128));
        controlPanel.setBackground(new Color(30, 80, 128));
        ImageIcon image = new ImageIcon("res/waiting.png");
        label = new JLabel(image);
        controlPanel.add(startTimeLabel);
        controlPanel.add(separatorLabel);
        controlPanel.add(endTimeLabel);
        controlPanel.add(replayButton);
        controlPanel.add(stopButton);
        controlPanel.add(previousButton);
        controlPanel.add(playPauseButton);
        controlPanel.add(nextButton);
        controlPanel.add(muteButton);
        controlPanel.add(volumeSlider);
        selectFolder.setText("Select Folder");
        selectFolder.addActionListener(evt -> selectFolderActionPerformed());

        /** Adds a listener to check the status of the timer slider*/
        timeSlider.setValue(0);
        /** TODO: Time skipping disabled due to time slider update interfering with skip
        * time slider update invokes changeListener causing audio issues */

        /*timeSlider.addChangeListener(e -> {
            JSlider source = (JSlider) e.getSource();
            if(!source.getValueIsAdjusting()){
                double time = (double)source.getValue();
                appPlayer.skip(time);
            }
        });*/

        /** Adds a listener to check the status of the volume slider*/
        volumeSlider.addChangeListener(e -> {
            JSlider source = (JSlider) e.getSource();
            if(!source.getValueIsAdjusting()){
                double volume = (double)source.getValue()/100.0;
                appPlayer.setVolume(volume);
            }
        });

        songTable.setAutoCreateRowSorter(true);
        songTable.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent me) {
                JTable table = (JTable) me.getSource();
                Point p = me.getPoint();
                int row = table.rowAtPoint(p);
                if(me.getClickCount()==2){
                    rowIndex = row;
                    appPlayer.stopSong();
                    appPlayer.startSong((String) songTable.getValueAt(row, 0), startTimeLabel, endTimeLabel);
                    playPauseButton.setIcon(new ImageIcon("res/pause.png"));
                }
            }
        });
        songTable.setModel(new DefaultTableModel(
                new Object [][] {},
                new String [] {
                        "Song", "Album", "Artist", "Genre"
                }
        ){
            public boolean isCellEditable(int row, int column) { return false; }
        });
        jScrollPane1.setViewportView(songTable);

        startTimeLabel.setText("00:00");
        startTimeLabel.setForeground(Color.WHITE);
        endTimeLabel.setText("00:00");
        endTimeLabel.setForeground(Color.WHITE);


        separatorLabel.setText("/");
        separatorLabel.setForeground(Color.WHITE);

        // ----------------------Buttons configuration ------------------------- //
        playPauseButton.setIcon(new ImageIcon("res/play.png"));
        playPauseButton.setContentAreaFilled(false);
        playPauseButton.addActionListener(new ActionListener() {
            boolean isPlaying = false;

            ImageIcon pauseIcon = new ImageIcon("res/pause.png");
            ImageIcon playIcon = new ImageIcon("res/play.png");
            @Override
            public void actionPerformed( ActionEvent arg0 )
            {
                rowIndex = songTable.getSelectedRow();
                if(hasSelectionChanged(selected, rowIndex)){
                    timeSlider.setValue(0);
                    selected = rowIndex;
                    appPlayer.stopSong();
                    appPlayer.startSong((String)songTable.getValueAt(rowIndex,0), startTimeLabel, endTimeLabel);
                    playPauseButton.setIcon(pauseIcon);
                }else if(isPlaying){
                    playPauseButton.setIcon(playIcon);
                    appPlayer.pauseSong();
                }else{
                    playPauseButton.setIcon(pauseIcon);
                    appPlayer.resumeSong();
                }
                isPlaying = !isPlaying;
            }
        });

        stopButton.setIcon(new ImageIcon("res/stop.png"));
        stopButton.setBackground(new Color(30, 80, 128));
        stopButton.setContentAreaFilled(false);
        stopButton.addActionListener(evt -> stopButtonActionPerformed(evt));

        muteButton.setIcon(new ImageIcon("res/sound_on.png"));
        muteButton.setBackground(new Color(30, 80, 128));
        muteButton.setContentAreaFilled(false);
        muteButton.addActionListener(new ActionListener() {
            boolean isMuted = true;
            ImageIcon muteIcon = new ImageIcon("res/sound_off.png");
            ImageIcon unmuteIcon = new ImageIcon("res/sound_on.png");
            @Override
            public void actionPerformed( ActionEvent arg0 )
            {
                if(isMuted){
                    muteButton.setIcon(muteIcon);
                    appPlayer.changeMuteStatus(isMuted);
                    isMuted = false;
                }else{
                    muteButton.setIcon(unmuteIcon);
                    appPlayer.changeMuteStatus(isMuted);
                    isMuted = true;
                }
            }
        });
        previousButton.setIcon(new ImageIcon("res/previous.png"));
        previousButton.setBackground(new Color(30, 80, 128));
        previousButton.setContentAreaFilled(false);
        previousButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timeSlider.setValue(0);
                selected = --rowIndex;
                appPlayer.stopSong();
                appPlayer.startSong((String)songTable.getValueAt(rowIndex,0), startTimeLabel, endTimeLabel);
                playPauseButton.setIcon(new ImageIcon("res/pause.png"));
            }
        });
        nextButton.setIcon(new ImageIcon("res/next.png"));
        nextButton.setBackground(new Color(30, 80, 128));
        nextButton.setContentAreaFilled(false);
        nextButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                timeSlider.setValue(0);
                selected = ++rowIndex;
                appPlayer.stopSong();
                appPlayer.startSong((String)songTable.getValueAt(rowIndex,0), startTimeLabel, endTimeLabel);
                playPauseButton.setIcon(new ImageIcon("res/pause.png"));
            }
        });

        replayButton.setIcon(new ImageIcon("res/replay.png"));
        replayButton.setBackground(new Color(30, 80, 128));
        replayButton.setContentAreaFilled(false);
        replayButton.addActionListener(evt -> replayButtonActionPerformed(evt));

        //----------------------End of Button Configuration----------------------//


        //---------------------------------------- Audio control layout -----------------------------------------//
        javax.swing.GroupLayout inferiorPanelLayout = new javax.swing.GroupLayout(inferiorPanel);
        inferiorPanel.setLayout(inferiorPanelLayout);
        inferiorPanelLayout.setHorizontalGroup(
                inferiorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(inferiorPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(inferiorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(timeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(controlPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
        );
        inferiorPanelLayout.setVerticalGroup(
                inferiorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inferiorPanelLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(timeSlider, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(controlPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
                leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 195, Short.MAX_VALUE)
                        .addComponent(label)
        );
        leftPanelLayout.setVerticalGroup(
                leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(label)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(64, 64, 64)
                                                .addComponent(selectFolder))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(inferiorPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(selectFolder)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inferiorPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }

    //---------------------------------------- End of audio control layout -----------------------------------------//

    /** This is audio file chooser event handler. The filter narrows the options to the three formats below.
     * If the file chooser has executed successfully the AppPlayer will receive the song
     * and make it ready to play.*/
    private void selectFolderActionPerformed() {

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(true);
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnValue = fileChooser.showOpenDialog(null);

        if(returnValue == JFileChooser.APPROVE_OPTION){
            File selectedFolder = fileChooser.getSelectedFile();
            appPlayer.importSongs(selectedFolder, songTable);
        }
    }

    /** Stop Button event handler*/
    private void stopButtonActionPerformed(ActionEvent evt) {
        appPlayer.stopSong();
    }

    private void replayButtonActionPerformed(ActionEvent evt) {
        toggleReplay = !toggleReplay;
        appPlayer.enableReplay(toggleReplay);
    }

    private boolean hasSelectionChanged(int old, int current){
        return (old != current);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //UIManager.put("nimbusBase", new Color(255,0,0));
        //UIManager.put("nimbusBlueGrey", new Color(0,255,0));
        UIManager.put("control", Color.LIGHT_GRAY);
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlayerWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlayerWindow().setVisible(true);
            }
        });
    }

    // Variables declaration
    private JLabel startTimeLabel;
    private JLabel endTimeLabel;
    private JLabel separatorLabel;
    private JPanel leftPanel;
    private JPanel controlPanel;
    private JPanel inferiorPanel;
    private JScrollPane jScrollPane1;
    private JButton muteButton;
    private JButton stopButton;
    private JButton previousButton;
    private JButton nextButton;
    private JButton replayButton;
    private JButton playPauseButton;
    private JButton selectFolder;
    private JTable songTable;
    private JSlider timeSlider;
    private JSlider volumeSlider;
    private AppPlayer appPlayer;
    private boolean toggleReplay;
    public static boolean disableSkip;
    public static JLabel label;
    int selected = -1;
    int rowIndex;
    // End of variables declaration
}
